### PR TITLE
Add IBM PCIe cards

### PR DESCRIPTION
**Pull request by spinler**
This adds configurations for the following cards that have similar
configs:

Flett - NVMe JBOF card
Bear River: 2U PCIe cable card
Bear Lake: 4U PCIe cable card

The TMP435s are on the same power domain as the PCIe slot itself and so
the sensor daemon needs to know that.  The PowerStateOwner JSON entry
tells hwmontempsensor this, and the LocationCode entry is used by
hwmontempsensor to find the associated PCIeSlot D-Bus object.

The TMP435s provide two temperatures, local and remote.  The remote one
is the interesting one so that is what the warning threshold is on.

This a downstream only commit because PowerStateOwner and LocationCode are only supported by downstream dbus-sensors code.

Signed-off-by: Matt Spinler <spinler@us.ibm.com>
Change-Id: I9e1802b88389f0db13870d64378316d0505edcb4

### CODE REVIEW

**Review by msbarth — APPROVED** [review]

**Comment by spinler** [comment]
I just noticed CI failed with something unrelated to my changes:
```
FAILED: src/entity-manager.p/Utils.cpp.o 
c++ -Isrc/entity-manager.p -I../include -I/usr/local/include -fdiagnostics-color=never -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -Werror -std=c++20 -g -Wno-psabi -DBOOST_COROUTINES_NO_DEPRECATION_WARNING -DBOOST_SYSTEM_NO_DEPRECATED -DBOOST_ERROR_CODE_HEADER_ONLY -DBOOST_NO_RTTI -DBOOST_NO_TYPEID -DBOOST_ALL_NO_LIB -DBOOST_ALLOW_DEPRECATED_HEADERS '-DPACKAGE_DIR="/usr/local/share/entity-manager/"' '-DSYSCONF_DIR="/usr/local/etc/entity-manager/"' -DBOOST_ASIO_DISABLE_THREADS -MD -MQ src/entity-manager.p/Utils.cpp.o -MF src/entity-manager.p/Utils.cpp.o.d -o src/entity-manager.p/Utils.cpp.o -c ../src/Utils.cpp
In file included from /usr/local/include/valijson/constraints/concrete_constraints.hpp:24,
                 from /usr/local/include/valijson/schema_parser.hpp:10,
                 from ../src/Utils.cpp:32:
/usr/local/include/valijson/constraints/basic_constraint.hpp:32:5: error: template-id not allowed for destructor
   32 |     ~BasicConstraint<ConstraintType>() override = default;
      |     ^
```

**Comment by spinler** [comment]
jenkins run tests please

**Comment by spinler** [comment]
We just need to pull the following into openbmc-build-scripts to pick up a newer valijson that has a C++20 fix: https://github.com/openbmc/openbmc-build-scripts/commit/68992895766fc9b2152a09a09c62f871d16515b6

**Comment by spinler** [comment]
jenkins run tests please

**Comment by spinler** [comment]
Now its:
```
clang/../src/FruUtils.cpp:100:20: error: use nullptr [modernize-use-nullptr,-warnings-as-errors]
    if (iter + len > end)
                   ^
                   nullptr
/home/fspcibld/openbmc-dev-jenkins/workspace/OpenBMC-Dev/build/github-public/repo-ci/public-ibm-openbmc-downstream-repo-ci-pr-entity-manager/ibm-openbmc/entity-manager/build-clang/../src/FruUtils.cpp:286:41: error: use nullptr [modernize-use-nullptr,-warnings-as-errors]
        if (fruBytesIter + fruBlockSize >= fruBytes.end())
                                        ^~
                                        nullptr
/home/fspcibld/openbmc-dev-jenkins/workspace/OpenBMC-Dev/build/github-public/repo-ci/public-ibm-openbmc-downstream-repo-ci-pr-entity-manager/ibm-openbmc/entity-manager/build-clang/../src/FruUtils.cpp:446:29: error: use nullptr [modernize-use-nullptr,-warnings-as-errors]
        for (; fruBytesIter < fruBytesIterEndArea; fruBytesIter++)
                            ^
                            nullptr
```

**Comment by spinler** [comment]
jenkins run tests please

**Comment by spinler** [comment]
jenkins run tests please

**Pull request merged**
